package de.subscripted.advancedvbanhammer.enums;

public enum ConfigMessage {
    WEBHOOK_URL,
    SENDER_IS_CONSOLE,
    PLAYER_NOT_FOUND,
    PLAYER_IS_BANNED,
    TEMP_BAN_USAGE,
    RELOAD_SUCCESS,
    PLAYER_BAN,
    BAN_USAGE,
    WRONG_BAN_ID,
    MUST_BE_A_NUMBER,
    TO_BIG_NUMBER,
    TEMP_BAN_MESSAGE,
    UNIT_NOT_EXISTING,
    NO_ONE_IS_BANNED,
    CHECK_IF_BANNED,
    CHECK_IS_BANNED,
    CHECK_IS_NOT_BANNED,
    PLAYER_IS_NOT_BANNED,
    UNBANNED_PLAYER,
    UNBAN_USAGE,
    PLAYER_BANNED_BROADCAST,
    PLAYER_TEMP_BANNED_BROADCAST,
    KICK_USAGE,
    PLAYER_KICK_DISCONNECT_SCREEN
}
